// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    extend: function(object, properties) {
      var key, val;
      for (key in properties) {
        val = properties[key];
        object[key] = val;
      }
      return object;
    },
    getRandomInt: function(min, max) {
      return Math.floor(Math.random() * (max - min + 1)) + min;
    },
    getRandomNumber: function() {
      return this.getRandomInt(0, 0x7fffffff);
    }
  };

}).call(this);
